## This file is a general .xdc for the Basys3 rev B board

## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
## Switches
# set_property PACKAGE_PIN V17 [get_ports {count}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {count}]
set_property PACKAGE_PIN V16 [get_ports {reset}]
	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
# set_property PACKAGE_PIN W16 [get_ports {upDown}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {upDown}]
# set_property PACKAGE_PIN W17 [get_ports {preset}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {preset}]
# set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
# set_property PACKAGE_PIN V15 [get_ports {sw[5]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
# set_property PACKAGE_PIN W14 [get_ports {sw[6]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
# set_property PACKAGE_PIN W13 [get_ports {sw[7]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
# set_property PACKAGE_PIN V2 [get_ports {sw[8]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
# set_property PACKAGE_PIN T3 [get_ports {sw[9]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
# set_property PACKAGE_PIN T2 [get_ports {sw[10]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
# set_property PACKAGE_PIN R3 [get_ports {sw[11]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
# set_property PACKAGE_PIN W2 [get_ports {value[0]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {value[0]}]
# set_property PACKAGE_PIN U1 [get_ports {value[1]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {value[1]}]
# set_property PACKAGE_PIN T1 [get_ports {value[2]}]					
	# set_property IOSTANDARD LVCMOS33 [get_ports {value[2]}]
set_property PACKAGE_PIN R2 [get_ports {showHour}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {showHour}]
 
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets count_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets speed_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets plus_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets minus_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets load_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets switch_IBUF]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {sound[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[0]}]
set_property PACKAGE_PIN E19 [get_ports {sound[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[1]}]
set_property PACKAGE_PIN U19 [get_ports {sound[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[2]}]
set_property PACKAGE_PIN V19 [get_ports {sound[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[3]}]
set_property PACKAGE_PIN W18 [get_ports {sound[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[4]}]
set_property PACKAGE_PIN U15 [get_ports {sound[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[5]}]
set_property PACKAGE_PIN U14 [get_ports {sound[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[6]}]
set_property PACKAGE_PIN V14 [get_ports {sound[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[7]}]
set_property PACKAGE_PIN V13 [get_ports {sound[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[8]}]
set_property PACKAGE_PIN V3 [get_ports {sound[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sound[9]}]
# set_property PACKAGE_PIN W3 [get_ports {Q_[10]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {Q_[10]}]
# set_property PACKAGE_PIN U3 [get_ports {Q_[11]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {Q_[11]}]
# set_property PACKAGE_PIN P3 [get_ports {led[12]}]
	# set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
# set_property PACKAGE_PIN N3 [get_ports {state[0]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
# set_property PACKAGE_PIN P1 [get_ports {state[1]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property PACKAGE_PIN L1 [get_ports {format}]
	set_property IOSTANDARD LVCMOS33 [get_ports {format}]
	
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN V7 [get_ports {currMode}]
	set_property IOSTANDARD LVCMOS33 [get_ports {currMode}]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports load]
	set_property IOSTANDARD LVCMOS33 [get_ports load]
set_property PACKAGE_PIN T18 [get_ports switch]						
	set_property IOSTANDARD LVCMOS33 [get_ports switch]
set_property PACKAGE_PIN W19 [get_ports minus]						
	set_property IOSTANDARD LVCMOS33 [get_ports minus]
set_property PACKAGE_PIN T17 [get_ports plus]						
	set_property IOSTANDARD LVCMOS33 [get_ports plus]
set_property PACKAGE_PIN U17 [get_ports speed]						
	set_property IOSTANDARD LVCMOS33 [get_ports speed]

##USB-RS232 Interface
#set_property PACKAGE_PIN B18 [get_ports RsRx]						
	#set_property IOSTANDARD LVCMOS33 [get_ports RsRx]
#set_property PACKAGE_PIN A18 [get_ports RsTx]						
	#set_property IOSTANDARD LVCMOS33 [get_ports RsTx]
